spring:

  # Virtual thread Configurations
  threads:
    virtual:
      enabled: true
  
  # PostgresSQL Database Connection Settings
  datasource:
    # The default HikariCP maximum pool size in Spring Boot is 10 connections.
    # During 10k RPS load testing, we need to increase the PostgreSQL connection pool 
    # to 300. To leverage these database connections, we must also increase the 
    # HikariCP pool size accordingly.    
    hikari:
      maximum-pool-size: 50
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  
  # JPA / Hibernate Configurations
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        #format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  
  # Redis Configurations
  data:
    redis:
      host: localhost
      port: 6379

  # Kafka Configurations
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: razorpay-clone-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.*"
    
  # OpenFeign client timeout cofiguration
  cloud.openfeign.client.config:
    merchant-service:
      connectTimeout: 5000
      readTimeout: 7000
    vault-service:
      connectTimeout: 5000
      readTimeout: 7000

# Eureka server Configurations
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    hostname: localhost

# Tracing and Metrics Configurations
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  tracing:
    sampling:
      probability: 0.1
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  metrics:
    tags:
      application: ${spring.application.name}

# Feign client global network configurations
# Enable HC5 pooling and 5s fail-fast timeouts to prevent thread starvation and support 10k RPS load testing
feign:
  httpclient:
    # Enable Apache HttpClient 5 for advanced connection pooling and HTTP/2 support
    hc5:
      enabled: true
  client:
    config:
      default:
        # Set fallback/global timeout thresholds across all Feign clients
        connectTimeout: 5000
        readTimeout: 5000    

# Logging Configurations
logging:
  level:
    org.apache.kafka.clients: WARN
    org.apache.kafka.common: WARN

app:
# Kafka topics Configurations
  kafka:
    topics:
      payment: payments.events
      order: orders.events
      refund: refunds.events
      settlement: settlements.events

# jwt topics Configurations
  jwt:
    secret-key: JWBq9AucykfpPXuwGELWOH3VG0sOOzso6IjAUG4jyIf

---

# --- indicates the start of a new YAML document (enables multi-document files)
# This configuration will used when K8S profile is active

spring:
  config:
    activate:
      on-profile: k8s
  data:
    redis:
      host: redis.razorpay-core.svc.cluster.local
      port: 6379
  kafka:
    bootstrap-servers: kafka.razorpay-core.svc.cluster.local:9092
  cloud:
    discovery:
      enabled: false
  task:
    scheduling:
      pool:
        size: 4

eureka:
  client:
    enabled: false
    register-with-eureka: false
    fetch-registry: false

management:
  zipkin:
    tracing:
      endpoint: http://zipkin.razorpay-core.svc.cluster.local:9411/api/v2/spans

MERCHANT_SERVICE_URI: http://merchant-service
PAYMENT_SERVICE_URI: http://payment-service
VAULT_SERVICE_URI: http://vault-service
OPERATIONS_SERVICE_URI: http://operations-service