server:
  port: 9040

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/razorpay-vault-db

vault:
  master-key: sKrpKUIxLLE1j9MBbYnPknL62c8kEbrBWflPVY7bxt6
  random-key-length: 12